import { supabase } from './supabaseClient';
import { authService, AuthUser } from './authService';
import { createSubscription, getCurrentPlan } from './subscriptionService';
import { PlanId } from '../types';

/**
 * Result of user registration
 */
export interface RegistrationResult {
  userId: string;
  email: string;
  requiresPlanSelection: boolean;
}

/**
 * Result of plan selection
 */
export interface PlanSelectionResult {
  requiresPayment: boolean;
  paymentUrl?: string;
}

/**
 * Registration Flow Service
 * Manages the user registration flow including plan selection and activation
 */
class RegistrationService {
  /**
   * Register a new user with email and password
   * Extends the existing authService.signUp functionality
   */
  async registerUser(email: string, password: string): Promise<RegistrationResult> {
    try {
      // Use existing auth service to create the user
      const user = await authService.signUp(email, password);

      // Check if user has selected a plan
      const hasSelected = await this.hasSelectedPlan(user.id);

      return {
        userId: user.id,
        email: user.email,
        requiresPlanSelection: !hasSelected,
      };
    } catch (error) {
      throw new Error(`Registration failed: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  }

  /**
   * Save the user's plan selection
   * Does not activate the plan yet - that happens in completeFreeRegistration or completePaidRegistration
   */
  async selectPlan(userId: string, planId: PlanId): Promise<PlanSelectionResult> {
    try {
      // Validate plan ID
      const validPlans: PlanId[] = ['free', 'starter', 'pro', 'business'];
      if (!validPlans.includes(planId)) {
        throw new Error(`Invalid plan ID: ${planId}`);
      }

      // Store the selected plan in user metadata
      const { error: updateError } = await supabase.auth.updateUser({
        data: {
          selected_plan: planId,
          plan_selection_date: new Date().toISOString(),
        },
      });

      if (updateError) {
        throw new Error(`Failed to save plan selection: ${updateError.message}`);
      }

      // Free tier doesn't require payment
      if (planId === 'free') {
        return {
          requiresPayment: false,
        };
      }

      // Paid plans require payment
      // The payment URL will be generated by the payment service
      return {
        requiresPayment: true,
        paymentUrl: undefined, // Will be set by payment service
      };
    } catch (error) {
      throw new Error(`Plan selection failed: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  }

  /**
   * Complete free tier registration
   * Activates the free plan with 5 image quota
   */
  async completeFreeRegistration(userId: string): Promise<void> {
    try {
      // Verify user is authenticated
      const currentUser = await authService.getCurrentUser();
      if (!currentUser || currentUser.id !== userId) {
        throw new Error('User not found or not authenticated');
      }

      // Create or update subscription with free plan
      const now = new Date();
      const periodEnd = new Date(now);
      periodEnd.setDate(periodEnd.getDate() + 30); // 30 days period

      const { error: subscriptionError } = await supabase
        .from('subscriptions')
        .upsert(
          {
            user_id: userId,
            plan_id: 'free',
            status: 'active',
            current_period_start: now.toISOString(),
            current_period_end: periodEnd.toISOString(),
            remaining_quota: 5, // Free tier gets 5 images
            auto_renew: true,
            updated_at: now.toISOString(),
          },
          {
            onConflict: 'user_id',
          }
        );

      if (subscriptionError) {
        throw new Error(`Failed to activate free subscription: ${subscriptionError.message}`);
      }

      // Log the activation
      await supabase.from('usage_logs').insert({
        user_id: userId,
        action: 'plan_changed',
        resource_type: 'subscription',
        metadata: {
          planId: 'free',
          quota: 5,
          registrationType: 'free',
        },
      });

      // Update user metadata to mark plan as activated
      await supabase.auth.updateUser({
        data: {
          plan_activated: true,
          activation_date: new Date().toISOString(),
        },
      });
    } catch (error) {
      throw new Error(`Free registration completion failed: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  }

  /**
   * Complete paid plan registration after successful payment
   * Activates the paid subscription with full quota
   */
  async completePaidRegistration(userId: string, paymentToken: string): Promise<void> {
    try {
      // Get the selected plan from user metadata
      const { data: { user }, error: userError } = await supabase.auth.getUser();
      
      if (userError || !user) {
        throw new Error('User not found or not authenticated');
      }

      // Try to get selected plan from user metadata first
      let selectedPlan = user.user_metadata?.selected_plan as PlanId;
      console.log('Plan from user_metadata:', selectedPlan);
      
      // If not in metadata, try localStorage (for payment callback scenarios)
      if (!selectedPlan || selectedPlan === 'free') {
        const pendingPlan = localStorage.getItem('pending_payment_plan');
        console.log('Plan from localStorage:', pendingPlan);
        console.log('All localStorage keys:', Object.keys(localStorage));
        
        if (pendingPlan && pendingPlan !== 'free') {
          selectedPlan = pendingPlan as PlanId;
          console.log('Using plan from localStorage:', selectedPlan);
        }
      }
      
      if (!selectedPlan || selectedPlan === 'free') {
        console.error('No paid plan found! user_metadata:', user.user_metadata, 'localStorage:', localStorage.getItem('pending_payment_plan'));
        throw new Error('No paid plan selected');
      }

      // Create the subscription using the subscription service
      await createSubscription(userId, selectedPlan, paymentToken);

      // Update user metadata to mark plan as activated
      await supabase.auth.updateUser({
        data: {
          plan_activated: true,
          activation_date: new Date().toISOString(),
        },
      });
      
      // Clean up localStorage after successful activation
      localStorage.removeItem('pending_payment_plan');
      localStorage.removeItem('pending_payment_credit_package');
    } catch (error) {
      throw new Error(`Paid registration completion failed: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  }

  /**
   * Check if user has selected a plan
   * Returns true if user has selected a plan (stored in user metadata)
   */
  async hasSelectedPlan(userId: string): Promise<boolean> {
    try {
      const { data: { user }, error } = await supabase.auth.getUser();
      
      if (error || !user || user.id !== userId) {
        return false;
      }

      // Check if user has selected_plan in metadata
      const selectedPlan = user.user_metadata?.selected_plan;
      return !!selectedPlan;
    } catch (error) {
      console.error('Error checking plan selection:', error);
      return false;
    }
  }

  /**
   * Check if user can access the main application
   * Returns true if user has an active subscription with quota or credits
   */
  async canAccessApp(userId: string): Promise<boolean> {
    try {
      // Check if user has an active subscription
      const subscription = await getCurrentPlan(userId);
      if (!subscription) {
        return false;
      }

      // Check if subscription is active
      if (subscription.status !== 'active') {
        return false;
      }

      // User can access the app if they have an active subscription
      // Even if quota is 0, they can still access to purchase credits or upgrade
      return true;
    } catch (error) {
      console.error('Error checking app access:', error);
      return false;
    }
  }

  /**
   * Reset user's plan selection and activation status
   * Useful when subscription is deleted or expired
   */
  async resetPlanSelection(userId: string): Promise<void> {
    try {
      // Clear plan selection and activation from user metadata
      await supabase.auth.updateUser({
        data: {
          selected_plan: null,
          plan_activated: false,
          plan_selection_date: null,
          activation_date: null,
        },
      });
    } catch (error) {
      console.error('Error resetting plan selection:', error);
      throw new Error(`Failed to reset plan selection: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  }
}

// Export singleton instance
export const registrationService = new RegistrationService();

